version: 3.11.0
runner.dialect: Scala213Source3
maxColumn: 120

rewrite {
  rules: [
    Imports
    PreferCurlyFors
    ProcedureSyntax
    RedundantBraces
    RedundantParens
    RemoveSemicolons
    SortModifiers
  ]

  imports {
    sort: scalastyle
    removeRedundantSelectors: true
  }

  redundantBraces {
    generalExpressions: false
    defnBodies: none
    stringInterpolation: true
  }

  trailingCommas.style: always
  sortModifiers.preset: styleGuide
}

align {
  openParenCallSite: false
  openParenDefnSite: false

  // don't align arrows in match statements
  preset: none
}

danglingParentheses {
  callSite: false
  defnSite: false
}

docstrings {
  style: Asterisk
  blankFirstLine: true
  removeEmpty: true
  wrap: fold
}

newlines.topLevelStatementBlankLines: [
  {
    regex: "Import"
    blanks: 1
  }
]

project.excludeFilters: [ "metals.sbt" ]

fileOverride {
  // sbt related files - *.sbt & project/*.scala
  "glob:**/*.sbt" {
    runner.dialect: sbt1
    // align libraryDependencies
    align.preset: most
  }
  "glob:**/project/*.scala" {
    runner.dialect: sbt1
    // align libraryDependencies
    align.preset: more
  }
}